### ISSUE TITLE
Page navigation rendering

### ISSUE THREAD

**Issue by raskolnikoov** [cofoundry-cms/cofoundry#141]
It would be nice to have some documentation on how you could build a page navigation with CoFoundry. I would like to see example of simple page navigation rendering and also with childpages navigation rendering for better help to create menus.

**Comment by HeyJoel** [comment]
This one has come up a couple of times so your right, we definitely need some better documentation here. Issue #89 covers improving functionality here, but documentation and samples are also needed.

For now all we have is:

- **[Cofoundry.Samples.Menus](https://github.com/cofoundry-cms/Cofoundry.Samples.Menus):** This is very bare-bones and just shows how to use the page routing helper from a child action to output menu items. This will definitely change when the 0.2 (net core) version is released since we don't have child actions in asp.net core.
- **[Cofoundry.Samples.PageModules](https://github.com/cofoundry-cms/Cofoundry.Samples.PageModules):** This sample shows how you can create page modules that reference directories or collections of pages. The same technique can be used with custom entities, so a good way to implement content managed menus would be to create a custom entity called *Menu* that has a Pages property annotated with `[PageCollectionAttribute]`. 

Once we have the net core migration out the way we'll be better positioned to be able to improve on this functionality.

**Comment by HeyJoel** [comment]
We've updated the [Cofoundry.Samples.Menus](https://github.com/cofoundry-cms/Cofoundry.Samples.Menus) sample to show a few different types of content manageable menus e.g. simple menus, nested menus and multi-level menus.

I think that should cover this issues, but do get in touch if you think we need more examples.
