### ISSUE TITLE
Question: external authentication?

### ISSUE THREAD

**Issue by unsafecode** [cofoundry-cms/cofoundry#156]
Is it possible to leverage some kind of external authentication, like OAuth2 providers? Maybe with a plugin?

**Comment by HeyJoel** [comment]
We don't have this built in yet, but I'd like to see this supported at some point via plugins for different providers.

What you can do is use the base functionality to log in a user that you have authenticated with an external system. This is what we've done in the past since our clients tend to have different SSO systems that require bespoke integration. There's a [sample project](https://github.com/HeyJoel/CofoundryExample.SSOAndContent) I made a while ago that demonstrates this, but it used the old .full-framework version of Cofoundry, although the principals and most of the apis remain the same. Most of the code you want is in the [MemberSignInService](https://github.com/HeyJoel/CofoundryExample.SSOAndContent/blob/master/CofoundryExample.SSOAndContent/Models/Domain/MemberUserArea/MemberSignInService.cs). I can get this updated if this interests you?

Are you looking to integrate a particular provider? For the admin panel or for a different user area? It would be useful for us to know a little more info to help us plan implementing this feature.

**Comment by unsafecode** [comment]
@HeyJoel Thanks for the sample. I'm definitely interested in the topic: our main goal is not to force **admin users** to register themselves, and rather enable re-using of some existing accounts. They might be MS accounts, for instance, while in other scenarios traditional NTLM/Windows Auth would suffice.

**Comment by HeyJoel** [comment]
I've updated the [SSO sample project](https://github.com/HeyJoel/CofoundryExample.SSOAndContent) to run on the latest (netcore) version of Cofoundry. The sample demonstrates using an external provider to log into a member user area, but you'll be interested in logging into the admin user area. The code will be much the same as the sample but you'll want to use `CofoundryAdminUserArea.AreaCode` in place of `MemberUserArea.AreaCode`.

I'm going to split out this issue as there's some docs work that needs doing and then the larger issue of expernal auth providers:

- #162 Provide better documentation for authentication 
- #163 External / SSO auth providers

I'm going to close this issue, but if you think the new issues do not cover your question do let me know.
