### ISSUE TITLE
IImageAssetFileService implementation

### ISSUE THREAD

**Issue by unsafecode** [cofoundry-cms/cofoundry#166]
I found pretty confusing and undocumented how to implement `IImageAssetFileService`, since the default one is empty and does NOT allow to store any image.

Did I miss the page on the docs? Or is there some example? So far I've been able to store image bytes in my own table, but I still don't see any image listed (and Cofoundry table on the db is empty as well).

**Comment by HeyJoel** [comment]
You'll need to install an image resizing plugin, as this is not handled by default. At the moment there is only [Cofoundry.Plugins.Imaging.ImageSharp](https://github.com/cofoundry-cms/Cofoundry.Plugins.Imaging.ImageSharp). This is a pre-release package because ImageSharp is in beta at the moment.

This is documented in the [images](https://github.com/cofoundry-cms/cofoundry/wiki/Images) section of the docs:

> Although we have image resizing APIs in Cofoundry, this is only supported with the use of a plugin. Server side image processing is a tricky area and the plugin you choose might depend on your platform or the way you want to scale.
> 
> Currently the only image resizing plugin available is Cofoundry.Plugins.Imaging.ImageSharp, which you can add via NuGet.

I'll add some info about this to the installation docs and also take a look at the content of the exception message that is thrown when you try and upload without the plugin.

**Comment by HeyJoel** [comment]
Reading back my response I should probably clarify that you do not need to implement `IImageAssetFileService` yourself, the image resizing plugin will handle this for you.

**Comment by unsafecode** [comment]
@HeyJoel OK, it took a me a bit longer than expected, but I managed to build a simple FileService implementation that stores small files on SQL via EF Core, along with the corresponding ImageAssetFileService.
