### ISSUE TITLE
Editor in Source mode remove i tag of html code

### ISSUE THREAD

**Issue by khanhtranchi** [cofoundry-cms/cofoundry#202]
When use editor in source mode to insert the html code, I found that the editor remove i tag. For example:
`<div class="icon-wrapper"><i class="icon-layers pulse-shrink"></i></div>`

will become `<div class="icon-wrapper">&nbsp;</div>`

How can I fix this case ?

Thanks.

**Comment by HeyJoel** [comment]
The TinyMCE html editor is removing your code as it is trying to clean it up. It appears to be doing two things:

1. Removing `i` tag because it is empty. Adding `nbsp;` prevents it from being removed
2. Replacing the `i` tag with an `em` tag which in most text editing scenarios is more semantically correct.

Generally I wouldn't expect you to be pasting chunks of layout html into the editor, it's really designed for editing rich text content in a WYSIWYG manner, where it is appropriate to clean-up pasted text input. You could instead add other properties to your page block that you could use to control the content renders in a more user friendly way.

If you do want complete as-is control over a block of html your rendering you could instead opt for a simple `[MultiLineText]` annotation instead and render to data as html.

Either way, do be aware of the [Html Sanitizer](https://github.com/cofoundry-cms/cofoundry/wiki/Html-Sanitizer) which also cleans up the output and protects against XSS.

Having said that there are some things we could improve here:

1. [Valid elements](https://www.tinymce.com/docs/demo/valid-elements/) and other [content filtering settings](https://www.tinymce.com/docs/configure/content-filtering/) can be configured in TinyMCE. We don't currently have a way to easily change this configuration but we should allow that.
2. Perhaps the naming of the `RawHtml` block type is misleading. We could look at this and whether there is a way to be more lenient with input validation when using this particular block type. However in most case I would expect you to create your own block type if you needed finer grained control of the editor/rendering.

**Comment by HeyJoel** [comment]
Thanks for the feedback. 

I've been working on making TinyMCE configuration available so you can customize it independently for each model property. The changes are now available in our [MyGet](https://www.myget.org/gallery/cofoundry) in the 0.3.2-beta00XX line of pre-release packages.

This will be documented for an upcoming release, but the idea is that you can either add configuration via a .NET type or via a config file path. So for example we could [configure TinyMCE to allow all elements](https://www.tinymce.com/docs/configure/content-filtering/#valid_elements):

```csharp
public class AllowAllElementsHtmlEditorConfigSource : IHtmlEditorConfigSource
{
    public IDictionary<string, object> Create()
    {
        // configure TinyMCE to permit all elements
        return new Dictionary<string, object>() 
        {
            { "valid_elements", "+*[*]" }
        };
    }
}

public class ExampleDataModel : IPageBlockTypeDataModel
{
    [Html(ConfigSource = typeof(AllowAllElementsHtmlEditorConfigSource))]
    public string HtmlClassConfig { get; set; }
}
```

Or define config in a simple json file:

``` csharp
public class ExampleDataModel : IPageBlockTypeDataModel
{
    [Html(ConfigFilePath = "/content/html-editor-config.json")]
    public string HtmlFileConfig { get; set; }
}
```

I need to move onto something else right now but I'll come back to this soon. So any feedback on this would be appreciated.

I need to put a little more thought into how we handle the RawHtml block type. If we applied more relaxed TinyMCE settings for that block type, would that suit most use-cases? Rendering would still have to pass through the html sanitizer, so you might still see inline javascript and non-whitelisted attributes stripped out.

Is anyone encountering scenarios where a code-editor would be preferable to an WYSIWIG html editor?

**Comment by HeyJoel** [comment]
@runxc1 I just got around to testing out your problem with escaping with multi-line text content. 

You'd get an escaping issue if you were using the *PlainText* block type, because it renders the text using our html [sanitizer](https://github.com/cofoundry-cms/cofoundry/wiki/Html-Sanitizer) which strips out potentially unsafe elements and attributes.

But if you were using the `[MultiLineText]` data annotation in a custom entity or you own block type then you could render the data however you want, even just using `@Html.Raw(myMultiLineTextField)` if you wanted to bypass the html sanitizer.

Making a [custom block type is pretty easy](https://github.com/cofoundry-cms/cofoundry/wiki/Page-Block-Types) so the built-in ones aren't designed to cover every eventuality. E.g. here's an example of a block type that just lets you enter raw code, which is rendered out without any sanitization:

**RawCodeDataModel.cs**
```csharp
using Cofoundry.Domain;

public class RawCodeDataModel : IPageBlockTypeDataModel, IPageBlockTypeDisplayModel
{
    [MultiLineText(Rows = 10)]
    public string Code { get; set; }
}
```

**RawCode.cshtml**
```html
@model RawCodeDataModel
@inject ICofoundryBlockTypeHelper<RawCodeDataModel> Cofoundry

@{
    Cofoundry.BlockType.UseDescription("Unrestricted raw code content");
    Layout = null;
}

@Html.Raw(Model.Code)
```

**Comment by runxc1** [comment]
So when I ran into the issue I was using a custom block type and also using Html.Raw.   The escaping issue was not that the script file was getting sanitized but rather it seemed like the page put the raw html into a json object on the page and it wasn't escaping the json correctly as json would be displayed at the bottom of the page.  As I only had one use for the custom block type I ended up just putting the script directly into the block type.

**Comment by HeyJoel** [comment]
@runxc1 thanks for this, I've replicated the issue and extracted it to #208

**Comment by HeyJoel** [comment]
With #203 and #208 complete I think this can be worked around by changing the TinyMCE configuration, documentation [here](https://github.com/cofoundry-cms/cofoundry/wiki/Html-Data-Model-Annotation#escaping-and-sanitizing).

I think there's still some questions around the default TinyMCE config and how we should be handling sanitization in the built-in RawHtml block type so I've opened #219 as a discussion item to try and work out what the best approach is for that specific issue, please add feedback if this area is important to you.
