### ISSUE TITLE
Open pdf file on browser

### ISSUE THREAD

**Issue by khanhtranchi** [cofoundry-cms/cofoundry#212]
Hi all,

I want to open a pdf file on browser like this link https://www.bestessays.com/samples/term_paper.pdf.
But I can not do that with pdf files that are uploaded through the document management in cms.
Could you guide me how to do that? I refer to this topic https://github.com/cofoundry-cms/cofoundry/wiki/Documents, but can not find the way to do.

Thanks.

**Comment by khanhtranchi** [comment]
Hi @HeyJoel ,

Do you mean in the way it opens in the browser windows rather than forcing a download?
--> Yes, I want to open pdf file in the browser window rather than download and open it with the pdf reader. 

If I upload file to wwwroot folder, I can open it on the browser window directly. I guess maybe the response header's controller need to clarify a little bit when returns FileResult like this post mention [https://stackoverflow.com/questions/6293893/how-do-i-force-files-to-open-in-the-browser-instead-of-downloading-pdf](url)

**Comment by HeyJoel** [comment]
Ok so it seems the Content-Disposition is set to attachment rather than inline. I'll have to do a bit of investigation as to what the correct default behaviour should be here with various file types, and whether we should provide an alternate route or mehod of generating links for inline display.

I suspect the best default will be removing the content-disposition altogether which will use the [default inline](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition), which is what the example term paper does. We can then provide an alternate route for download (content-disposition: attachment) or the developer can use the [anchor download attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) to control this from the view.

**Comment by HeyJoel** [comment]
I've fixed the document download to use the expected default "inline" content disposition and added alternate routes to the `IDocumentAssetRouteLibrary` and `IContentRouteLibrary` that generate links that force a download using the old behaviour (with content disposition "attachment").

The document block type has also been updated to allow users to choose whether to have the document display inline or force a download.

This will be released in v0.3.2
