### ISSUE TITLE
BasicTestSite Internal error 

### ISSUE THREAD

**Issue by ernestoSerra** [cofoundry-cms/cofoundry#238]
Hi, 
I'm starting with Cofoundry and I have a problem when I publish the BasicTestSite on my remote IIS through Visual Studio as Web Deploy. 
This error can be seen using app.UseDeveloperExceptionPage() in startup.cs class. 

![internal error](https://user-images.githubusercontent.com/8802992/44856142-0039c980-ac6d-11e8-8ddb-e41962b85e43.PNG)

I think this error is caused at the moment that application runs and it try to create the Cofoundry tables in the database, but I could not find the problem. 
I publish the original BasicTestSite, without any change. If I execute it through visual studio in local IIS it runs succesfull. 

Thanks

**Comment by HeyJoel** [comment]
The error is "Incorrect syntax near 'THROW'", which is usually because you're trying to run the site on a version of SQLServer earlier than 2012 which does not support the `throw` keyword. 

Cofoundry only runs on SQLServer 2012 or later. It's worth mentining that SQLServer 2008 R2 is out of mainstreem support and [only has a year left on extended support](https://blogs.msdn.microsoft.com/sqlreleaseservices/end-of-mainstream-support-for-sql-server-2008-and-sql-server-2008-r2/) (sept 2019).

**Comment by ernestoSerra** [comment]
The problem was solved by installing the latest version of sql server, thanks.
