### ISSUE TITLE
Custom Entity Duplication

### ISSUE THREAD

**Issue by moe-uxa** [cofoundry-cms/cofoundry#242]
new feature Custom Entity Duplication is duplicating the entity without publishing it, even if the entity is marked as auto-publish. 
I was trying to retrieve some custom entity values using GetCustomEntityRenderSummariesByIdRangeAsync and not all of them were retrieved, they only got retrieved after I edited and re-saved the duplicated entity.

**Comment by HeyJoel** [comment]
Ok thanks, I see why that's happened. When you duplicate an entity that does not have auto-publish enabled, then it should be duplicated as draft so that is expected functionality, but if auto-publish is enabled then it should be published, so that is where the bug is.

The workaround for now, as you say, is to edit and save the entity which will mark it as published.

**Comment by HeyJoel** [comment]
Fixed, will be released in v0.5
