### ISSUE TITLE
Plugins.

### ISSUE THREAD

**Issue by kiranbchitari** [cofoundry-cms/cofoundry#251]
How to add plugins.

**Comment by HeyJoel** [comment]
Hi, is this related to:

- How to add an existing plugin e.g. [Imaging.ImageSharp](https://github.com/cofoundry-cms/Cofoundry.Plugins.Imaging.ImageSharp)?
- How to create a new plugin NuGet package?
- How to add some sort of functionality to Cofoundry?

Or something else? Please can you add some clarification.

**Comment by HeyJoel** [comment]
Installing a plugin is typically as simple as installing a NuGet package, but I can see some gaps in our documentation so I've added some docs for [Installing a plugin](https://github.com/cofoundry-cms/cofoundry/wiki/Installing-Plugins) and a listing of [available plugins](https://github.com/cofoundry-cms/cofoundry/wiki/Available-Plugins).

If you need any further clarification do let me know, otherwise I'll close this off.

**Comment by Shilpakopparad** [comment]
> Installing a plugin is typically as simple as installing a NuGet package, but I can see some gaps in our

I Installed as like Nuget Packages. Actually, I'm trying that Youtube example. It is showing that page not found.

**Comment by HeyJoel** [comment]
The YouTube example does not seed any data, you'll need to create a page in the admin UI first in order to edit content.

What exactly are you having problems with? Note that the youtube/vimeo plugins just provide you the data attribute, it's up to you to use it in your page block or custom entity data models.
