### ISSUE TITLE
Issue with CMS admin login

### ISSUE THREAD

**Issue by gtannen** [cofoundry-cms/cofoundry#260]
When you attempt to login to the CMS administration back-end (and with the correct credentials), the screen does not redirect to the dashboard, but instead remains on the login screen itself. As such, the client is unable to login to the CMS.

This is a production issue and the site is available here - https://hcp.yakult.co.uk/admin/auth/login 

If you could contact me separately, I can share credentials which you can use to see the issue.

Anything you can do to help?

Gareth

**Comment by HeyJoel** [comment]
Hi, it sounds like the login is not setting the auth cookie correctly. If you check the network traffic you'll probably see the login attempt to redirect to dashboard and then instantly redirect back to login because the auth cookie was not set on the login request.

If this was working correctly and now is not then it would be important to know if anything changed either in the codebase or the hosting environment. 

One thing to look for is that you're running https and so you'll need to make sure the request is secure all the way back to the server as the auth cookie uses [CookieSecurePolicy.SameAsRequest](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.cookiesecurepolicy?view=aspnetcore-2.1) and therefore the auth cookie will be discarded if it arrives on an unsecure connection. Issue #195 details some possible solutions.

**Comment by HeyJoel** [comment]
Microsoft also has some guidance here on [Configure ASP.NET Core to work with proxy servers and load balancers](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.1)

**Comment by gtannen** [comment]
Thanks for the quick responses. Nothing has changed in the codebase for the CMS back-end as I understand we're using the Nuget package DLLs there. 

Yes this was working in production until around 2 weeks ago and then it stopped, so we're at a bit of loss as to what could have cause it to break - what would you suspect, environment-wise, would cause this kind of issue? The SSL has been there when it was working too.

In our local dev environment, we're running a Windows VM with SSL and the issue does not occur. So it must be something between Azure App Services, SSL and Cofoundry?

**Comment by gtannen** [comment]
We just restarted the Azure App Service and it solved the problem. Strange!

**Comment by HeyJoel** [comment]
Hi Gareth, with the extra info you provided I took another look into the issue and found a bug that would have caused your problem. I've fixed that now and it will be included in the v0.5 release which I'll try and get pushed out soon, hopefully in a weeks time.
