### ISSUE TITLE
How to get page instance in page block

### ISSUE THREAD

**Issue by dumboster** [cofoundry-cms/cofoundry#266]
Hello,
Is there a simple way to get the page instance in a _page block type_ ? I need to get the "PageRoutingHelper" property in a _page block type_.
Thanks

**Comment by HeyJoel** [comment]
It's missing from the docs, but you can get access to the parent page instance by inheriting from `IPageBlockWithParentPageData` in your block type display model.

The model will be cast to the `IEditablePageViewModel` type, but you can test for and cast to `IPageRoutableViewModel` to get access to the routing helper.

Having said that I'm not too keen on the design of `PageRoutingHelper`, as it uneccessarily loads the page routing structure on all page requests whether you need it or not, so that might be something we change. It's possible that we could lazy-load it from the CofoundryHelper instead (as we do with `ICurrentUserViewHelper`). 

Which properties of the `PageRoutingHelper` are you interested in?

**Comment by dumboster** [comment]
Thanks for these details.
I need it for breadcrumb. I took my inspiration from your code : BreadcrumbUIControlExtension, method GetBreadcrumbs. So I need : CurrentPageRoute, VisualEditorMode, CurrentPageVersionId, PageRoutes, PageDirectoryRoutes.

**Comment by HeyJoel** [comment]
Closing, design work for this feature has been moved into #272
