### ISSUE TITLE
Image resizing

### ISSUE THREAD

**Issue by dumboster** [cofoundry-cms/cofoundry#271]
Hello,
We can resize images as we want via IImageResizeSettings and its great, but isn't there a risk of attack with loading a lot of different sizes for images, as each image is cached on disk? Is there a safeguard?
Thanks

**Comment by HeyJoel** [comment]
In terms of DDOS I would say it's the resizing operation that is expensive rather than serving file off the disk cache. What we have in place currently is the ability to set the max resize width/height which defaults to 3200px to prevent overly large image sizes being requested which would otherwise consume large amounts of memory. This can be lowered even further to reduce the risk if you don't need such large images.

We also have a settings flag that disables image resizing completely if you want to rely on users uploading files as set sizes. The `[Image]` data attribute can be used to set a specific size if your want to limit your users to assigning specific image sizes to properties.

These config settings documented [here](https://github.com/cofoundry-cms/cofoundry/wiki/Common-Config-Settings#imageassetsettings)

I looked into this a bit with the recent changes to assets and concluded that there wasn't a straightforward simple and effective way to add more restrictions. Some ideas were to implement:

- Settings for minimum resize size
- Settings for size increments (e.g. multiples of 10px, 100px)
- An api to whitelist IImageResizeSettings

Generally I felt that even if you had these configured that you'd still be able to generate a fair amount of resized images. The disk caching mitigates the performance issues with resizing so the main issue is that you'd end up with a lot of files, but disk space isn't all that expensive these days.

I'm open to ideas or suggestion on this one.

**Comment by dumboster** [comment]
Ok, thanx for tour response.

**Comment by HeyJoel** [comment]
I'm going to close this for now.

One thing to add is that if you're scaling up and this is a concern then it wouldn't be too much effort to either wrap the service that resizes images or replace the controller action that serves up the images.

It's also feasible to isolate the image serving functionality in a separate application if you wanted to host and scale it separately. None of this is documented, just possible, and if anyone is interesting in doing this sort of stuff then let me know and I'll look into writing up a bit more information about it.
