### ISSUE TITLE
Exceptions when attempting to edit Custom Entity template region

### ISSUE THREAD

**Issue by jhaygood86** [cofoundry-cms/cofoundry#284]
When attempting to edit a custom entity region you get 1 of 2 errors depending on whether or not a draft version exists:

1. If a draft exists, you get a validation that a Draft Version already exists
2. If a draft doesn't exist, you get a null reference exception in Toolbar.cshtml on line 75 in the Visual Editor -- it looks that "Version" in the PageResponseData is null for some odd reason

Note that when the second case happens, refreshing the page gets the first error.

The custom entity region is defined as:

    @(await Cofoundry.Template.CustomEntityRegion("Body")
                    .AllowBlockType<RawHtmlDataModel>()
                    .EmptyContentMinHeight(500)
                    .InvokeAsync())

This is with Cofoundry 0.5.1 from nuget

**Comment by HeyJoel** [comment]
Hi, I can't replicate this in the [Simple Sample](https://github.com/cofoundry-cms/Cofoundry.Samples.SimpleSite) project with the blog entity. One thing to check first is that you haven't made alterations in the database manually or are running in a multi-server environment, because it sounds like the application cache might be out of date.

In the admin panel, if you go to *Settings* > *Site Settings* and click on the *Clear Cache* button, does it fix the error? Restarting the site will also clear the in-memory cache.

Otherwise, perhaps you could post the custom entity definition for me as it might be because you have a specific set of settings that isn't working.

**Comment by jhaygood86** [comment]
I've tried restarting the application many times. It's pretty easy to reproduce.

The custom entity definition is:

    public class PostEntityDefinition : ICustomEntityDefinition<PostDataModel>
    {
        public const string PostEntityDefinitionCode = "BPPOST";

        public string CustomEntityDefinitionCode => PostEntityDefinitionCode;

        public string Name => "Post";

        public string NamePlural => "Posts";

        public string Description => "Posts are content elements that are strongly linked to time, such as news or blog";

        public bool ForceUrlSlugUniqueness => false;

        public bool HasLocale => false;

        public bool AutoGenerateUrlSlug => false;

        public bool AutoPublish => false;
    }

    public class PostDataModel : ICustomEntityDataModel
    {
        [Display(Name = "Post Title")]
        public string Title { get; set; }
    }

page section is like I said.

Essentially, go to the Custom Entity edit page in the Admin panel, and click "Manage in Visual Editor" on the Body Region under the Template: Posts area

**Comment by jhaygood86** [comment]
Figured it out! It might be something that needs to be documented.

When writing a custom query in a ICustomEntityRoutingRule, the query handler needs to explictly include CustomEntityVersions for the CustomEntity, since it looks like lazy loading is not enabled in the CofoundryDbContext
