### ISSUE TITLE
Canonical url

### ISSUE THREAD

**Issue by ernestoSerra** [cofoundry-cms/cofoundry#304]
Hi, 
we see that Cofoundry supports canonical urls, but is there any way to configure it or is it not implemented yet?

Thanks.

**Comment by HeyJoel** [comment]
I'm not sure what aspect of canonical urls you're referring to, because it's up to you how you want to implement that meta information in your pages, but here's some info on parts of Cofoundry you might use to construct your urls:

## Defining a canonical url from a string

The simplest example is to create canonical url from a string. We can use the [Cofoundry view helper](https://www.cofoundry.org/docs/content-management/cofoundry-view-helper) to turn this into an absolute url which is required for canonical urls.

```html
@{
    var url = Cofoundry.Routing.ToAbsolute("/my-static-url");
}

<meta property="og:url" content="@Html.Raw(url)" />
<link rel="canonical" href="@Html.Raw(url)" />
```

By default `Cofoundry.Routing.ToAbsolute("/my-static-url")` will use the host and scheme of the incoming request to create the url, but it's a better idea to set this manually in your config using the `Cofoundry:SiteUrlResolver:SiteUrlRoot` setting to make sure it's always the same, even if you have multiple domains mapped to the same resource.

So for the Cofoundry site our config looks like this:

```
{
  "Cofoundry": {
    "SiteUrlResolver:SiteUrlRoot": "https://www.cofoundry.org"
  }
}
```

## Getting the url of Cofoundry pages and custom entities

For dynamic pages in Cofoundry we provide you a path for the page in the model, which you can use to construct your canonical url meta tag. Typically I would either pass the path up to the layout page using `ViewBag` or define a meta section in the layout view file and implement the meta section in the template file; it's just Razor templating so use whatever you prefer.

#### Page Templates

```html
@model PageViewModel
@inject ICofoundryTemplateHelper<PageViewModel> Cofoundry

@{
    var canonicalUrl = Model.Page.PageRoute.FullPath;
}
```

#### Custom Entity Pages

```html
@model CustomEntityPageViewModel<ExampleEntityPageDisplayModel>
@inject ICofoundryTemplateHelper<CustomEntityPageViewModel<ExampleEntityPageDisplayModel>> Cofoundry

@{
    var canonicalUrl = Model.CustomEntity.Model.FullPath;
}
```
