### ISSUE TITLE
Image FileNameOnDisk

### ISSUE THREAD

**Issue by ArcaneTSGK** [cofoundry-cms/cofoundry#314]
Issue: When uploading a file using Cofoundry CMS admin with the ImageSharp plugin, the image is saved to disk with an arbitrary name, such as {ImageAssetId}-xxxxxxxxx.png

Expectation: The file saved on the server under 'App_Data' should be the name of the image

Essentially we are attempting to use Cofoundry as a headless CMS, exposing API's and consuming them with our static Gatsby site. The images need to therefore be retrievable at Gatsby Build, but with these filenames it makes them not SEO friendly. 

Unless I am missing something, I can't find a way of exposing the images for the front end to consume.

**Comment by HeyJoel** [comment]
Hi there,

The file naming strategy in Cofoundry is key in allowing us to have files that are updateable, permanently cacheable and non-conflicting in a dynamic site environment. 

SEO friendly url translation happens at runtime so that we don't have to update the image file every time someone updates the title, we therefore avoid tricky file locking issues and can also issue SEO friendly  301 redirects to avoid broken links.

So there's a good reason not to have dynamic assets named using their titles on disk.

I've not worked with Gatsby in depth, but I'd be surprised if there wasn't a way to translate the filename in the publish process, and on the Cofoundry side, the `ImageAssetRenderDetails` model should give you all the data you need to do that including the `FileNameOnDisk` and `Title` property.

Alternatively, you could download the images dynamically served by Cofoundry using the `ImageAssetRenderDetails.Url` property, this url will have the dynamically generated SEO-friendly file name. Again, I'm not overly familiar with Gatsby but [createRemoteFileNode](https://www.gatsbyjs.org/packages/gatsby-source-filesystem/#createremotefilenode) looks worth investigating.
