### ISSUE TITLE
Default Cofoundry Schema in Core module

### ISSUE THREAD

**Issue by ArcaneTSGK** [cofoundry-cms/cofoundry#315]
Issue: We require a CMS for multiple products, but our DBA would like to manage all CMS tables under one Database which will have a schema per product

Is it possible to change the Cofoundry.Core.DbConstants.CofoundrySchema to something else in the Startup or otherwise prior to it creating the initial tables, then we could have something like {product}.Cofoundry

Thanks

**Comment by HeyJoel** [comment]
Thats not possible rightnow. The schema is baked into the installation and other db objects and so that's not trivial to change.

Conceptually I'm not yet in favor of multiple instances per database, as the db provides a good level of isolation. The main argument I can think of is with cost saving associated with certain methods of db hosting, but then we have to consider the cost implication of developing and maintaining quite an invasive feature.

I'd be interested to hear other good reasons for developing this feature.

**Comment by ArcaneTSGK** [comment]
Thank you for your quick response,

For our DBA's it's just extra maintenance and overhead, having to back up multiple databases etc...

We will however off the back of this do one database per product that requires a CMS.
