### ISSUE TITLE
Deploy Cofoundry to IIS 

### ISSUE THREAD

**Issue by mrccarvalho** [cofoundry-cms/cofoundry#327]
Hi,

I found an error after deployed to IIS Web server.
It runs normally locally.
The connection string is good. The "appsettings" file is present.

I found this error in logs file.
ERROR:

"fail: Cofoundry.Web.AutoUpdateHostedService[0]
      Error executing update
Cofoundry.Core.Configuration.InvalidConfigurationException: DatabaseSettings configuration invalid: The ConnectionString field is required."

Thanks,
Roger Carvalho

**Comment by HeyJoel** [comment]
This error means the config setting "Cofoundry:Database:ConnectionString" is missing. Cofoundry uses the built-in [configuration settings system in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2), so the issue is likely to be outside of Cofoundry.

**Comment by mrccarvalho** [comment]
Thanks HeyJoel!

you are right, in the appsettings file, i have "**Database**" twice, so the connectionString could not be read.
