### ISSUE TITLE
How to order Customentity NamePlural ? 

### ISSUE THREAD

**Issue by ramkrish3020** [cofoundry-cms/cofoundry#337]
![image](https://user-images.githubusercontent.com/20699474/62362424-870cbb80-b53a-11e9-83a6-1b3199143d29.png)
How to order Customentity NamePlural, Can you please help me on this?

Thanks!

**Comment by HeyJoel** [comment]
It's not currently possible to change the order of the admin menu, this is covered by issue #160, as there is a wider job to improve the menu and allow customization. The ordering currently has dashboard at the top (because it is the default item) and then has the main content types (pages, images etc) ahead of any custom elements, which are listed in order.
