### ISSUE TITLE
Template Region in Custom Entity Page Template

### ISSUE THREAD

**Issue by mcockrellsana** [cofoundry-cms/cofoundry#348]
Hello again!

I was wondering if there is currently a way possible to define template regions in custom entity page templates?  I tried using the Cofoundry.Template.Region definition but was met with an un editable property on the page definition in the back end and unable to modify it on the front end in admin edit view.

I know theres a Cofoundry.Template.CustomEntityRegion definition, but this applies the region data only to the specific custom entity ID you're on.  What I would like is a region that I can edit on one custom entity ID page, and it applies to all the custom entities using that template.

Is this a possibility?

**Comment by HeyJoel** [comment]
Hello! Yes, that should be possible. It gets a bit confusing having both page editable regions and custom entity ediable regions in a template, but it is supported - i think we need to work on the visual editor UI to make it clearer how that works though - it's good to know you've found a use-case for it.

Firstly, regions are displayed in the admin panel, but are only editable in the visual editor view (in-page), so that's why they are un-editable in the admin panel view.

Secondly, if you have both custom entity and page regions in the same template, you should get an option to switch between editing each in the visual editor, e.g. here I can switch between editing the "blog" custom entity and the page "template":

![image](https://user-images.githubusercontent.com/2780344/65338816-e85c1d00-dbc2-11e9-93ae-ae596ae52476.png)

Be sure you are formatting your regions correctly e.g:

```html
<div class="container">

    <div class="row content-block">
        <div class="col-sm-12">
            <h1>@Model.PageTitle</h1>
        </div>
    </div>

    @(await Cofoundry.Template.CustomEntityRegion("Example Blog Region")
        .AllowMultipleBlocks()
        .AllowBlockType<ContentSectionDataModel>()
        .AllowBlockType<ContentSplitSectionDataModel>()
        .EmptyContentMinHeight(500)
        .InvokeAsync())

        <div class="col-sm-4">
         
            @(await Cofoundry.Template.Region("Example Page Region")
                .AllowMultipleBlocks()
                .EmptyContentMinHeight(500)
                .InvokeAsync())

        </div>
    
</div>
```

**Comment by HeyJoel** [comment]
Closing - inactive.

**Comment by NiiAnyetei** [comment]
Hi. Please I'm getting an update exception "Cofoundry.Domain.PageTemplateRegistrationException: Dulpicate template region ' What We Do' in template /Cofoundry/PageTemplates/_Home.cshtml"

**Comment by HeyJoel** [comment]
@NiiAnyetei i expect it's something to do with the underscore in your file name, did you change it recently? A colleague of mine had a similar issue when he cppy/pasted his template and renamed with an underscore. I'm not at my laptop right now but i think the underscores are removed when making the module name and so there can be a clash if you have similarly named files.
