### ISSUE TITLE
Which is the status and roadmap of cofoundry?

### ISSUE THREAD

**Issue by biapar** [cofoundry-cms/cofoundry#361]
Which is the status and roadmap of cofoundry?

**Comment by HeyJoel** [comment]
Hi @biapar, the project has been mostly on hold this year since we lost funding. We hope to start things back up soon, but it's difficult to predict how things will turn out. Unfortunately it's a substantial project and it's not sustainable to run it in my spare time.

There's a couple of [releases in the pipeline](https://github.com/cofoundry-cms/cofoundry/milestones), and 0.6.2 isn't too far off being finished. Hopefully we can get back to working on those releases soon.

**Comment by HeyJoel** [comment]
With 0.7 and 0.8 out the door, we're getting a little more caught up. 0.9 should be release should be out soon too as most of the major work it done. Keep an eye on the [milestones](https://github.com/cofoundry-cms/cofoundry/milestones) for roadmap information.

News on sponsors, ways to financially contribute and the sustainability of the project will come in time. Closing this for now.
