### ISSUE TITLE
Caching Dependency Registration issue in 0.8.0

### ISSUE THREAD

**Issue by greencmg** [cofoundry-cms/cofoundry#399]
Trying to develop a SQL Distribution Cache for use in Azure, I utilized the BasicTestSite example and was somewhat successful in implementing in 0.7.0 --  When updated to 0.8.0, the registration recognized the injection but still defaults to InMemory.  

In Addition, using the SQL Distributed Cache and trying to follow the InMemoryObject Cache, the CustomEntities (Blog and Category) which I assume falls under PageRoutes, do not get cached and not available under Admin.  I must be implementing this incorrectly. When I switch back to InMemory and they comeback.  Your guidance is much appreciated. 
![cache](https://user-images.githubusercontent.com/3173193/105405116-9f194480-5bdf-11eb-9da6-b39e3e45a9f2.png)

Code:
[SQL - Caching.zip](https://github.com/cofoundry-cms/cofoundry/files/5851771/SQL.-.Caching.zip)

**Comment by HeyJoel** [comment]
So, what do you mean by "the registration recognized the injection", do you mean the dependency registration runs, but if you request an instance of `IObjectCacheFactory` you get the `InMemoryObjectCacheFactory`?

In your example code you have copied the `IObjectCacheFactory` and put it in a different namespace, why is that? Your DI registration references the `IObjectCacheFactory` in your new namespace `Cofoundry.BasicTestSite.Caching;`, so Cofoundry will never pick that up because your registering a different interface to that which it is using.

You imply that the upgrade to 0.8.0 caused the fault, but did you make any other changes? Are you sure it was working correctly in 0.7? I don't believe anything changed with cachingin that release.

Are you using the 0.8 NuGet packages or are you linking directly to the source? You reference the "BasicTestSite" project, but that's a test playground for the Cofoundry source, not an example project.

**Comment by HeyJoel** [comment]
No further info provided, closing.
