### ISSUE TITLE
the application is being updated. please try again shortly

### ISSUE THREAD

**Issue by endrehegyi** [cofoundry-cms/cofoundry#442]
Hi,

I have been successfully running a .net core 2.1 app on a shared hosting platform (smarterasp), with a db on that same platform. 

I've now tried to migrate to DigitalOcean VPS where I have other sites running well (no cofoundry). 

After setting up routing etc.. I run the application and it just stays on 
"the application is being updated. please try again shortly"

I'm really stuck as to why this is happening?

It's connected to the same database.
It works fine if I run it locally.

**Comment by HeyJoel** [comment]
That message occurs while Cofoundry is trying run the auto-updater, it locks out the application while it is doing this and if an exception occurs it will wait for a moment and re-try, hoping that the error has been resolved (e.g. intermittent db failure).

I would suspect that if you have just set this up that there is an issue connecting to the database e.g. connection string or firewall/permissions. 

If you need to see the error and the site isn't yet public you can enable the developer exception page by setting the `Cofoundry:Debug:DeveloperExceptionPageMode` setting to `On`, see [Debug Setting](https://www.cofoundry.org/docs/references/common-config-settings#debugsettings). Or if you enable .NET logging to the filesystem you can inspect the error there.

**Comment by HeyJoel** [comment]
[The default port for SQLServer is 1433](https://duckduckgo.com/?t=ffab&q=sqlserver+default+port&atb=v229-1), but it can be changed. 

Do you mean that you have your db on one host and your app server on another?

**Comment by endrehegyi** [comment]
Yes I have my db on the old original host (I haven't moved it) and then my app server on Digital Ocean.

**Comment by JornWildt** [comment]
If you use the same "old" connection string on the new website then it is very likely that either 1) the database host name is unknown on the Internet and thus unreachable from the new webserver, or 2) the database is blocked by a firewall to protect it from outside access.

Have you tried to connect to the database from your own development machine? Does that work? If so, then maybe there is an outgoing firewall rule on the new webserver (which would be a bit odd)?

**Comment by endrehegyi** [comment]
It connects and works with well if ran from a dev machine. So the host should be accessible, I can also connect to just the db from my local dev machine np. On the app server I have 'Ngnx Full' on my firewall which allows HTTP and HTTPS only (:80,:443) ports.

**Comment by HeyJoel** [comment]
Have you checked the error yet to verify that the issue is with the database connection?

**Comment by endrehegyi** [comment]
Yes checked it with the added Cofoundry DeveloperExceptionPage setting On but still it's the same, no extra information.

**Comment by HeyJoel** [comment]
There's a few things you can try.

1. Enable .NET logging to the file system and check for errors
2. Disable the auto update process so you can see if the applications runs without it. Use setting `Cofoundry:AutoUpdate:Disabled`, set it to `true`.
3. Check the distributed lock table to see if a lock is being added `select * from Cofoundry.DistributedLock where DistributedLockId = 'COFUPD'` - if the date is recent it means the application is connecting to the database and is able to create a lock. If this is the case then something else is the problem. You can check the ModuleUpdateError table to see if there is an error running the installation for a particular module: `select * from Cofoundry.ModuleUpdateError` - I doubt this is the case though, because you say that nothing has changed in the installation.
4. Is your old instance still connected to the database? It shouldn't matter if the applications are the same, as Cofoundry will startup fine in a multi-server environment, but I wonder if the old instance might be holding the lock? I guess then the other instance would also be showing the "updating" page though.

**Comment by endrehegyi** [comment]
I've tried all and this is what I got:

1. no error messages 
2. no visible change
3. no entries in those 2 db tables,
4. The old instance is connected to the db yes. I can also connect to that same db from a local machine without issues. 

I think the request to the db from the server is blocked somehow on DigitalOcean,
or MSSQL connections don't work on Ubuntu 20.04 on DigitalOcean,

**Comment by HeyJoel** [comment]
It's been a while since Cofoundry ran on .NET Core 2.1, which version of Cofoundry are you running?

**Comment by HeyJoel** [comment]
Closing - inactive.
