### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by nikunj-89** [cofoundry-cms/cofoundry#514]
There is no suitable example for pagination. With html file. If it is their very useful to developers.

**Comment by HeyJoel** [comment]
Cofoundry only supplies the data for your application; how you render that or express the paging UX is up to you. There's no specific UI sample because there are countless ways in which you could implement it. The data is detailed in the [paging docs](https://www.cofoundry.org/docs/framework/data-access/paged-queries#ipagedqueryresult).
