### ISSUE TITLE
Get Blog Post Details.

### ISSUE THREAD

**Issue by sourabhCofoundry** [cofoundry-cms/cofoundry#524]
Hii team I have faced an issue I have reverted to a previous version of the blog post details But It's an issue - PublishStatusQuery.SpecificVersion is not supported in GetCustomEntityRenderSummariesByDefinitionCodeQuery.
![Screenshot_10](https://user-images.githubusercontent.com/80239301/209538610-8df61f14-c71a-4fe4-942e-a5ba8c05fb13.png)

**Comment by HeyJoel** [comment]
From your screenshot it looks like you have not "reverted" to the version, but are instead "viewing" that version (that is the button you have highlighted). To revert to that version, you'd need to select the "copy to draft" button, which will make a copy of that version as the latest draft, and then publish it.

So, I guess that the problem you have is that you're trying to view a specific version, but some of the code you have in that page uses `GetCustomEntityRenderSummariesByDefinitionCodeQuery` and it's not returning the version you expect? Unfortunately, because `GetCustomEntityRenderSummariesByDefinitionCodeQuery` returns multiple entities, you can't request a specific version of just one of those entities, it's just not designed to be used that way and will throw an exception if you do. Other queries that target and return a single entity can be used to target a specific version e.g. `GetCustomEntityRenderSummaryByIdQuery` or `GetCustomEntityRenderSummariesByUrlSlugQuery`.

**Comment by HeyJoel** [comment]
Closing, no further info.
