### ISSUE TITLE
Improve TTI score.

### ISSUE THREAD

**Issue by sourabhCofoundry** [cofoundry-cms/cofoundry#527]
Hello, team please let me know if I have faced an issue  TTI score being very low. Please let me know How to improve the TTI score cofoundry cms.

**Comment by HeyJoel** [comment]
A slow TTI could be down to many reasons, many if them not to do with Cofoundry specifically. It could be due to the way you're fetching large amounts of Cofoundry data, but that is very implementation specific. 

As with any application you need to measure performance and understand what parts of the request are taking the most time. 

You haven't provided enough info for me to help you.
