### ISSUE TITLE
PermissionValidationFailedException

### ISSUE THREAD

**Issue by JornWildt** [cofoundry-cms/cofoundry#530]
This is more of a question ...

I have copied from the UserArea sample and I believe I managed to login a user. Unfortunately this piece of code in _Layout.cshtml fails:

```
@{
  var member = await Cofoundry.CurrentUser.GetAsync(MemberUserArea.Code);
}
```

What I get is:

```
PermissionValidationFailedException: Permission Validation Check Failed. Permission Type: Cofoundry.Domain.RoleReadPermission. UserId: 6

Cofoundry.Domain.Internal.PermissionValidationService.EnforcePermission(IPermissionApplication permission, IUserContext userContext)
Cofoundry.Domain.Internal.PermissionValidationService.EnforcePermission(IEnumerable<IPermissionApplication> permissions, IUserContext userContext)
Cofoundry.Domain.Internal.ExecutePermissionValidationService.Validate<TQuery, TResult>(TQuery query, IQueryHandler<TQuery, TResult> queryHandler, IExecutionContext executionContext)
Cofoundry.Domain.CQS.Internal.QueryExecutor.ExecuteQueryAsync<TQuery, TResult>(TQuery query, IExecutionContext executionContext)
Cofoundry.Domain.CQS.Internal.QueryExecutor.ExecuteAsync<TResult>(IQuery<TResult> query, IExecutionContext executionContext)
Cofoundry.Web.Internal.CurrentUserViewHelper.GetHelperContextAsync(IUserContext userContext)
Cofoundry.Web.Internal.CurrentUserViewHelper.GetAsync(string userAreaCode)
AspNetCore._Views_Shared__Layout.ExecuteAsync() in _Layout.cshtml
+
  var member = await Cofoundry.CurrentUser.GetAsync(FreelancerUserArea.Code);
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewCon
```

Unfortuantely I do not see anything I can do about elevating permissions.

I get the same kind of errors in signin code like this, which is straight of of the examples:

```
            // First authenticate the user without signing them in
            var authResult = await _contentRepository
                .WithModelState(this)
                .Users()
                .Authentication()
                .AuthenticateCredentials(new AuthenticateUserCredentialsQuery()
                {
                    UserAreaCode = MemberUserArea.Code,
                    Username = Email,
                    Password = Password
                })
                .ExecuteAsync();
```

I need to add `WithElevatedPermissions()` everywhere ... am I doing something wrong since it is not required in the examples?

**Comment by JornWildt** [comment]
It may be worth noticing that the _Layout file shows fine in a fresh private browser window without a current user ... until I login.

**Comment by JornWildt** [comment]
After a some fiddling I re-implemented the role definition and called this to update the roles:

```
      await _contentRepository
        .WithElevatedPermissions()
        .Roles()
        .RegisterPermissionsAndRoles(new RegisterPermissionsAndRolesCommand { UpdateExistingRoles = true });
```

(not exactly an easy way to fix an error in the role definition).

And lo-and-behold it now works.

So the failure was to make sure the newly created user's member area has enough permissions assigned to it:

```
    public void ConfigurePermissions(IPermissionSetBuilder builder)
    {
      builder
          .IncludeAll()
      //    .ExcludeAllDelete()
      //    .ExcludeUserInAllUserAreas()
      //    .ExcludeRole()
          .IncludeRole(rolePermissions => rolePermissions.Read())
      //    .ExcludeSettings(settingsPermissions => settingsPermissions.UpdateGeneral());
      ;
    }
```

So, the end-issue is is something like:

1) It would be *really* nice if role/permissions could be reloaded automatically. For instance by setting something in the app-config file that would force them to reload every time the system restarts. Or pointing out that I can reset them from the admin page if possible?

2) It is fairly impossible to guess what a good configuration for ConfigurePermissions() is. How am I supposed to know what permissions to include to be able to show if the current user is logged in or not ... and how do I go figure what more I need ... or if I have assigned too many permissions, making the user an admin?

Sorry for the frustration that might leak out :-)

**Comment by HeyJoel** [comment]
So the cause of the issue looks to be that your user didn't have the read role permission, which I can see you've tried to correct but then there's a few things that didn't work as you expected. First I should explain why it works the way it does:

- The role-read permission is required to read the basic role information to assign to your user account. I guess it's an akward technicality that you can deny permissions to this, as it's rare you'd want to.
- Permissions are not updated automatically because this would overwrite any configuration made in the admin UI. This is important where we want to define a set of roles in code, but leave any ongoing administration to website admins.
- Role permissions are defined using a set of include/exclude rules. Although you could define an include rule for each and every entity and/or permission, using rules allows you to set permissions more generally on a broader set of requirements. This also allows for roles to pick up new permissions that match the rules when they are added to the system automatically e.g. so you don't have to do it manually every time you add a new custom entity. Lastly, this also allows for plugins and modules to use the same API via extension methods.

Some existing things that might have made it easier:

- [Inheriting base permissions from the anonymous role](https://www.cofoundry.org/docs/framework/roles-and-permissions/managing-roles#configuring-permissions-in-code) would provide the baseline read permissions you need to access things like roles. I guess if you then exluded all role permissions afterwards, that wouldn't solve the issues.

Some things we could do to make it easier:

- In the docs, lead with the common use-case example of inheriting from anonymous defaults rather than the more complicated example.
- Perhaps we could look at separate permissions for "owned" entities e.g. "access the role I am assigned", and perhaps users should always have access to the role they are associated with. I'd need to take a deep dive into the repercussions of that.
- Throw more informative exceptions
- Optionally allow a role to be managed only from code, so that permissions are always synchronized, but are not editable via the Admin UI.
- Document use of the `RegisterPermissionsAndRolesCommand`, although this is quite a destructive way to apply permissions and you'd probably only want to do that in dev, or for one particular role.

More specifically to your comment:

> It is fairly impossible to guess what a good configuration for ConfigurePermissions() is

I'm open to suggestion as to how to improve this. I expect most people don't want to think too granular about permissions, and in that case we do have methods like `builder.IncludeAllRead()`. Perhaps if we sort out the gotchas it isn't so much of an issue?

**Comment by JornWildt** [comment]
Ha, never got past the initial `ConfigurePermissions()` example. It would probably have helped me a lot if I had manage to focus and read the `ApplyAnonymousRoleConfiguration()` part too!

Thanks.
